apiVersion: v1
kind: PersistentVolume
metadata:
 name: docker-registry-pv
spec:
 storageClassName: manual
 capacity:
  storage: 10Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/mnt/registry-data"
