version: "2.1"
commands:
  build_image:
    steps:
      - run:
          name: Build Docker Images
          command: docker build -t mypythonapp:latest -f Dockerfile .
jobs:
  build_and_push:
    parameters:
      dockerfile_name:
        type: string
        default: Dockerfile
      repo_name:
        type: string
    docker:
      - image: cimg/base:2021.04
    steps:   
      - checkout
      - setup_remote_docker
      - build_image
workflows:
  development:
    jobs:
      - build_and_push:
          dockerfile_name: Dockerfile
          repo_name: 'ranjan0620/docker-registry'
          filters:
            branches:
              only: master
