#ADDED COMMENT
version: '2.1'
orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  kubernetes: circleci/kubernetes@0.12.0
  aws-eks: circleci/aws-eks@0.2.3
  aws-cli: circleci/aws-cli@1.2.1

jobs:
  build_and_push:
    parameters:
      dockerfile_name:
        type: string
        default: Dockerfile
      repo_name:
        type: string
    docker:
      - image: cimg/base:2021.04
    steps:   
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: false
          dockerfile: << parameters.dockerfile_name >>
          no-output-timeout: 20m
          region: AWS_DEFAULT_REGION
          repo: << parameters.repo_name >>
          skip-when-tags-exist: false
          tag: "latest,$CIRCLE_SHA1"
  # k8_deploy:
  #   parameters:
  #     repo_name:
  #       type: string
  #   docker:
  #     - image: 'circleci/python:3.7.1'
  #   steps:
  #     - checkout
  #     - kubernetes/install-kubectl
  #     - aws-cli/setup:
  #         aws-access-key-id: AWS_ACCESS_KEY_ID
  #         aws-region: AWS_DEFAULT_REGION
  #         aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  #     - aws-eks/update-kubeconfig-with-authenticator:
  #         cluster-name: '$EKS_CLUSTER_NAME'
  #         aws-region: '$AWS_DEFAULT_REGION'  
  #     - kubernetes/create-or-update-resource:
  #         get-rollout-status: true
  #         resource-file-path: k8s/statefulSet.yml
  #         resource-name: statefulsets/vader-curtain
  #         show-kubectl-command: true
  #     - kubernetes/update-container-image:
  #         container-image-updates: "vader-curtain=$AWS_REPO_ID.dkr.ecr.us-east-1.amazonaws.com/<<parameters.repo_name>>:$CIRCLE_SHA1"
  #         get-rollout-status: true
  #         record: true
  #         resource-name: statefulsets/vader-curtain
  #     - slack/notify:
  #         event: fail
  #         template: basic_fail_1
  #     - slack/notify:
  #         event: pass
  #         template: basic_success_1

workflows:
  production:
    jobs:
      - build_and_push:
          dockerfile_name: Dockerfile
          repo_name: 'vdta'
          filters:
            branches:
              only: ranjan/vdta-test
          context: VDTA
      # - k8_deploy:
      #     repo_name: 'vader-curtain'
      #     requires:
      #       - build_and_push
      #     filters:
      #       branches:
      #         only: main
      #     context: VADER