version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: docker-registry-service.dev.fs.identv.com/newimage
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$MYREGISTRY_PASS" | docker login docker-registry-service.dev.fs.identv.com -u "$MYREGISTRY_USER" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
