version: "2.1"
executors:
  base_image:
    docker:
      - image: cimg/base:2020.01

commands:
  # Setting up docker layer caching
  
  # Logging into ECR
  
  # Build docker images
  build_image:
    steps:
      - run:
          name: Build Docker Images
          command: docker build -t mypythonapp:latest -f Dockerfile .
jobs:
  build_and_push:
    
    steps:
      - checkout
      - build_image
      
workflows:
  version: 2
  staging:
    jobs:
      - build_and_push:
          filters:
            branches:
              only:
                - master
